### ISSUE TITLE
Warning: preg_match(): Compilation failed: UTF-8 error: overlong 2-byte sequence at offset 9

### ISSUE THREAD

**Issue by MatzeKitt** [pluginkollektiv/antispam-bee#587]
**Describe the bug**
I got the following error message in Antispam Bee v3:

```
ErrorException: Warning: preg_match(): Compilation failed: UTF-8 error: overlong 2-byte sequence at offset 9
#8 /wp-content/plugins/antispam-bee/src/Rules/RegexpSpam.php(147): AntispamBee\Rules\RegexpSpam::verify
#7 /wp-content/plugins/antispam-bee/src/Handlers/Rules.php(39): AntispamBee\Handlers\Rules::apply
#6 /wp-content/plugins/antispam-bee/src/Handlers/Reaction.php(33): AntispamBee\Handlers\Reaction::process
#5 /wp-content/plugins/antispam-bee/src/Handlers/Comment.php(52): AntispamBee\Handlers\Comment::process
#4 /wp-includes/class-wp-hook.php(324): WP_Hook::apply_filters
#3 /wp-includes/plugin.php(205): apply_filters
#2 /wp-includes/comment.php(2243): wp_new_comment
#1 /wp-includes/comment.php(3671): wp_handle_comment_submission
#0 /wp-comments-post.php(25): null
```

The comment has not been saved, so I don’t know its actual content, unfortunately. While such a comment is pretty sure bad, we should prevent such an error from happen.

**Expected behavior**
No error occurs.

**Comment by 2ndkauboy** [comment]
Would it make sense to use the HTML API to parse the content instead of using a RegEx in the new version? :thinking:

**Comment by MatzeKitt** [comment]
This would require bumping the required WordPress version from currently 4.5 to at least 6.2.

**Comment by 2ndkauboy** [comment]
Fixed in https://github.com/pluginkollektiv/antispam-bee/pull/818
